#!/usr/bin/env bash
# Build + publish the admin dashboard on this droplet.
#
# Steps:
#   1. (cd dashboards/admin && npm ci && npm run build) — produces dist/.
#   2. Read the admin password hash from /etc/full-throttle/.admin-password.hash
#      (generated by install_server.sh's step_admin_password).
#   3. Render the Caddy fragment from infra/caddy/aggregator-admin.caddy.example
#      with the supplied --admin-domain and the hash, drop at
#      /etc/full-throttle/caddy.d/aggregator-admin.caddy.
#   4. systemctl reload caddy.
#
# Usage (run as root):
#     ./deploy_admin_dashboard.sh --admin-domain admin.<ip>.nip.io
#     ./deploy_admin_dashboard.sh --admin-domain admin.example.com --skip-build

set -euo pipefail

ADMIN_DOMAIN=""
SKIP_BUILD=0

while [ $# -gt 0 ]; do
  case "$1" in
    --admin-domain) ADMIN_DOMAIN="$2"; shift 2 ;;
    --skip-build)   SKIP_BUILD=1; shift ;;
    -h|--help)
      sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

[ -n "$ADMIN_DOMAIN" ] || { echo "missing --admin-domain" >&2; exit 2; }
[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

INFRA_DIR="$(cd "$(dirname "$0")" && pwd)"
PLATFORM_DIR="$(cd "${INFRA_DIR}/.." && pwd)"
ADMIN_DIR="${PLATFORM_DIR}/dashboards/admin"
HASH_FILE=/etc/full-throttle/.admin-password.hash
FRAGMENT=/etc/full-throttle/caddy.d/aggregator-admin.caddy

log() { printf '\033[1;36m[deploy-admin]\033[0m %s\n' "$*"; }

[ -d "$ADMIN_DIR" ] || { echo "missing $ADMIN_DIR" >&2; exit 1; }
[ -f "$HASH_FILE" ] || {
  echo "missing $HASH_FILE — run install_server.sh first to generate it" >&2
  exit 1
}

if [ "$SKIP_BUILD" -eq 0 ]; then
  log "building SPA in $ADMIN_DIR"
  cd "$ADMIN_DIR"
  if [ -f package-lock.json ]; then
    sudo -u hermes npm ci --no-audit --no-fund
  else
    sudo -u hermes npm install --no-audit --no-fund
  fi
  sudo -u hermes npm run build
  [ -f "${ADMIN_DIR}/dist/index.html" ] || {
    echo "build did not produce dist/index.html" >&2; exit 1
  }
else
  log "skipping build (--skip-build); using existing dist/"
fi

log "rendering Caddy fragment → $FRAGMENT (domain=$ADMIN_DOMAIN)"
HASH_CONTENT=$(cat "$HASH_FILE")
# {{ADMIN_PASSWORD_HASH}} contains $-signs from bcrypt; sed-escape them.
HASH_ESCAPED=$(printf '%s\n' "$HASH_CONTENT" | sed -e 's/[\/&]/\\&/g')
sed \
  -e "s|{{ADMIN_DOMAIN}}|${ADMIN_DOMAIN}|g" \
  -e "s|{{ADMIN_PASSWORD_HASH}}|${HASH_ESCAPED}|g" \
  "${INFRA_DIR}/caddy/aggregator-admin.caddy.example" > "$FRAGMENT"
chmod 0644 "$FRAGMENT"

log "validating + reloading Caddy"
caddy validate --config /etc/caddy/Caddyfile >/dev/null
systemctl reload caddy

log "live URL: https://${ADMIN_DOMAIN}/"
log "credentials: user=admin (password printed by install_server.sh)"
log "try:"
log "  curl -fsSI https://${ADMIN_DOMAIN}/healthz"
log "  curl -fsSI -u admin:<password> https://${ADMIN_DOMAIN}/api/admin/platform/stats"
